# Generated by Django 4.2.3 on 2023-07-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='view',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
