# Generated by Django 4.2.3 on 2023-07-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='view',
            field=models.CharField(default='view', max_length=10),
        ),
    ]
