# Generated by Django 4.2.3 on 2023-07-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='view',
        ),
    ]
